### ISSUE TITLE
Did you find any errors?

### ISSUE THREAD

**Issue by sunxingheng** [JK88-1337/Pandownload-fake-server#2]
File "/www/wwwroot/pandownload-fake-server/script.py", line 18
    print "Serving HTTP on", sa[0], "port", sa[1], "..."
                          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Serving HTTP on", sa[0], "port", sa[1], "...")?
  File "/www/wwwroot/pandownload-fake-server/script.py", line 18
    print "Serving HTTP on", sa[0], "port", sa[1], "..."
                          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Serving HTTP on", sa[0], "port", sa[1], "...")?
  File "/www/wwwroot/pandownload-fake-server/script.py", line 18
    print "Serving HTTP on", sa[0], "port", sa[1], "..."
                          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Serving HTTP on", sa[0], "port", sa[1], "...")?
  File "/www/wwwroot/pandownload-fake-server/script.py", line 18
    print （"Serving HTTP on", sa[0], "port", sa[1], "..."）
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(（"Serving HTTP on", sa[0], "port", sa[1], "..."）)?
Traceback (most recent call last):
  File "/www/wwwroot/pandownload-fake-server/script.py", line 2, in <module>
    import BaseHTTPServer
ModuleNotFoundError: No module named 'BaseHTTPServer'
Traceback (most recent call last):
  File "/www/wwwroot/pandownload-fake-server/script.py", line 3, in <module>
    from SimpleHTTPServer import SimpleHTTPRequestHandler
ModuleNotFoundError: No module named 'SimpleHTTPServer'
Traceback (most recent call last):
  File "/www/wwwroot/pandownload-fake-server/script.py", line 15, in <module>
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib64/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib64/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/www/wwwroot/pandownload-fake-server/script.py", line 15, in <module>
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib64/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib64/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/www/wwwroot/pandownload-fake-server/script.py", line 15, in <module>
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib64/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib64/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/www/wwwroot/pandownload-fake-server/script.py", line 15, in <module>
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib64/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib64/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
[2020-06-08 16:08:53 +0800] [47969] [INFO] Starting gunicorn 20.0.4
[2020-06-08 16:08:53 +0800] [47969] [INFO] Listening at: http://0.0.0.0:7787 (47969)
[2020-06-08 16:08:53 +0800] [47969] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2020-06-08 16:08:53 +0800] [47972] [INFO] Booting worker with pid: 47972
[2020-06-08 16:08:54 +0800] [47972] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/pandownload-fake-server/fake_venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/pandownload-fake-server/fake_venv/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/www/wwwroot/pandownload-fake-server/fake_venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/www/wwwroot/pandownload-fake-server/fake_venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/pandownload-fake-server/fake_venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/pandownload-fake-server/fake_venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/pandownload-fake-server/fake_venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/pandownload-fake-server/fake_venv/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/www/wwwroot/pandownload-fake-server/fake_venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/www/wwwroot/pandownload-fake-server/script.py", line 18
    print "Serving HTTP on", sa[0], "port", sa[1], "..."
                          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Serving HTTP on", sa[0], "port", sa[1], "...")?
[2020-06-08 16:08:54 +0800] [47972] [INFO] Worker exiting (pid: 47972)
[2020-06-08 16:08:54 +0800] [47969] [INFO] Shutting down: Master
[2020-06-08 16:08:54 +0800] [47969] [INFO] Reason: Worker failed to boot.

**Comment by JK88-1337** [comment]
under what conditions are you running this script?
please specify

**Comment by JK88-1337** [comment]
`File "/www/wwwroot/pandownload-fake-server/script.py", line 18
print "Serving HTTP on", sa[0], "port", sa[1], "..."
^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Serving HTTP on", sa[0], "port", sa[1], "...")?
File "/www/wwwroot/pandownload-fake-server/script.py", line 18
print "Serving HTTP on", sa[0], "port", sa[1], "..."
^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Serving HTTP on", sa[0], "port", sa[1], "...")?
File "/www/wwwroot/pandownload-fake-server/script.py", line 18
print "Serving HTTP on", sa[0], "port", sa[1], "..."
^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Serving HTTP on", sa[0], "port", sa[1], "...")?
File "/www/wwwroot/pandownload-fake-server/script.py", line 18
print （"Serving HTTP on", sa[0], "port", sa[1], "..."）`

oops, maybe this issue could be cause by the missing bracket after "print" since py3 made "print a function"

**Comment by JK88-1337** [comment]
there might be some **huge** versioning problems in this script.
`import BaseHTTPServer`
`ModuleNotFoundError: No module named 'BaseHTTPServer'`

Basic HTTP server is too old and may no longer be supported
